services:
  broker:
    build:
      context: ./broker
    container_name: mqtt-fcm-broker
    ports:
      - "1883:1883"   # MQTT
      - "8888:8888"   # Admin/UI
      - "8051:8051"   # Broker internal port
    env_file:
      - ./broker/.env
    restart: unless-stopped